from setuptools import setup

setup(
    name='Electro',
    version='1.0',
    packages=['Python.lib.python3.5.site-packages.pip', 'Python.lib.python3.5.site-packages.pip._vendor',
              'Python.lib.python3.5.site-packages.pip._vendor.idna',
              'Python.lib.python3.5.site-packages.pip._vendor.pytoml',
              'Python.lib.python3.5.site-packages.pip._vendor.certifi',
              'Python.lib.python3.5.site-packages.pip._vendor.chardet',
              'Python.lib.python3.5.site-packages.pip._vendor.chardet.cli',
              'Python.lib.python3.5.site-packages.pip._vendor.distlib',
              'Python.lib.python3.5.site-packages.pip._vendor.distlib._backport',
              'Python.lib.python3.5.site-packages.pip._vendor.msgpack',
              'Python.lib.python3.5.site-packages.pip._vendor.urllib3',
              'Python.lib.python3.5.site-packages.pip._vendor.urllib3.util',
              'Python.lib.python3.5.site-packages.pip._vendor.urllib3.contrib',
              'Python.lib.python3.5.site-packages.pip._vendor.urllib3.contrib._securetransport',
              'Python.lib.python3.5.site-packages.pip._vendor.urllib3.packages',
              'Python.lib.python3.5.site-packages.pip._vendor.urllib3.packages.backports',
              'Python.lib.python3.5.site-packages.pip._vendor.urllib3.packages.ssl_match_hostname',
              'Python.lib.python3.5.site-packages.pip._vendor.colorama',
              'Python.lib.python3.5.site-packages.pip._vendor.html5lib',
              'Python.lib.python3.5.site-packages.pip._vendor.html5lib._trie',
              'Python.lib.python3.5.site-packages.pip._vendor.html5lib.filters',
              'Python.lib.python3.5.site-packages.pip._vendor.html5lib.treewalkers',
              'Python.lib.python3.5.site-packages.pip._vendor.html5lib.treeadapters',
              'Python.lib.python3.5.site-packages.pip._vendor.html5lib.treebuilders',
              'Python.lib.python3.5.site-packages.pip._vendor.lockfile',
              'Python.lib.python3.5.site-packages.pip._vendor.progress',
              'Python.lib.python3.5.site-packages.pip._vendor.requests',
              'Python.lib.python3.5.site-packages.pip._vendor.packaging',
              'Python.lib.python3.5.site-packages.pip._vendor.cachecontrol',
              'Python.lib.python3.5.site-packages.pip._vendor.cachecontrol.caches',
              'Python.lib.python3.5.site-packages.pip._vendor.webencodings',
              'Python.lib.python3.5.site-packages.pip._vendor.pkg_resources',
              'Python.lib.python3.5.site-packages.pip._internal',
              'Python.lib.python3.5.site-packages.pip._internal.req',
              'Python.lib.python3.5.site-packages.pip._internal.vcs',
              'Python.lib.python3.5.site-packages.pip._internal.utils',
              'Python.lib.python3.5.site-packages.pip._internal.models',
              'Python.lib.python3.5.site-packages.pip._internal.commands',
              'Python.lib.python3.5.site-packages.pip._internal.operations', 'Python.lib.python3.5.site-packages.past',
              'Python.lib.python3.5.site-packages.past.tests', 'Python.lib.python3.5.site-packages.past.types',
              'Python.lib.python3.5.site-packages.past.utils', 'Python.lib.python3.5.site-packages.past.builtins',
              'Python.lib.python3.5.site-packages.past.translation', 'Python.lib.python3.5.site-packages.yaml',
              'Python.lib.python3.5.site-packages.PyQt5', 'Python.lib.python3.5.site-packages.PyQt5.uic',
              'Python.lib.python3.5.site-packages.PyQt5.uic.Loader',
              'Python.lib.python3.5.site-packages.PyQt5.uic.port_v2',
              'Python.lib.python3.5.site-packages.PyQt5.uic.port_v3',
              'Python.lib.python3.5.site-packages.PyQt5.uic.Compiler', 'Python.lib.python3.5.site-packages.isort',
              'Python.lib.python3.5.site-packages.numpy', 'Python.lib.python3.5.site-packages.numpy.ma',
              'Python.lib.python3.5.site-packages.numpy.ma.tests', 'Python.lib.python3.5.site-packages.numpy.doc',
              'Python.lib.python3.5.site-packages.numpy.fft', 'Python.lib.python3.5.site-packages.numpy.fft.tests',
              'Python.lib.python3.5.site-packages.numpy.lib', 'Python.lib.python3.5.site-packages.numpy.lib.tests',
              'Python.lib.python3.5.site-packages.numpy.core', 'Python.lib.python3.5.site-packages.numpy.core.tests',
              'Python.lib.python3.5.site-packages.numpy.f2py', 'Python.lib.python3.5.site-packages.numpy.f2py.tests',
              'Python.lib.python3.5.site-packages.numpy.tests', 'Python.lib.python3.5.site-packages.numpy.compat',
              'Python.lib.python3.5.site-packages.numpy.compat.tests',
              'Python.lib.python3.5.site-packages.numpy.linalg',
              'Python.lib.python3.5.site-packages.numpy.linalg.tests',
              'Python.lib.python3.5.site-packages.numpy.random',
              'Python.lib.python3.5.site-packages.numpy.random.tests',
              'Python.lib.python3.5.site-packages.numpy.testing',
              'Python.lib.python3.5.site-packages.numpy.testing.tests',
              'Python.lib.python3.5.site-packages.numpy.testing._private',
              'Python.lib.python3.5.site-packages.numpy.distutils',
              'Python.lib.python3.5.site-packages.numpy.distutils.tests',
              'Python.lib.python3.5.site-packages.numpy.distutils.command',
              'Python.lib.python3.5.site-packages.numpy.distutils.fcompiler',
              'Python.lib.python3.5.site-packages.numpy.matrixlib',
              'Python.lib.python3.5.site-packages.numpy.matrixlib.tests',
              'Python.lib.python3.5.site-packages.numpy.polynomial',
              'Python.lib.python3.5.site-packages.numpy.polynomial.tests', 'Python.lib.python3.5.site-packages.wrapt',
              'Python.lib.python3.5.site-packages.Cython', 'Python.lib.python3.5.site-packages.Cython.Plex',
              'Python.lib.python3.5.site-packages.Cython.Build',
              'Python.lib.python3.5.site-packages.Cython.Build.Tests',
              'Python.lib.python3.5.site-packages.Cython.Tests', 'Python.lib.python3.5.site-packages.Cython.Runtime',
              'Python.lib.python3.5.site-packages.Cython.Tempita', 'Python.lib.python3.5.site-packages.Cython.Utility',
              'Python.lib.python3.5.site-packages.Cython.Compiler',
              'Python.lib.python3.5.site-packages.Cython.Compiler.Tests',
              'Python.lib.python3.5.site-packages.Cython.Debugger',
              'Python.lib.python3.5.site-packages.Cython.Debugger.Tests',
              'Python.lib.python3.5.site-packages.Cython.Distutils', 'Python.lib.python3.5.site-packages.future',
              'Python.lib.python3.5.site-packages.future.moves', 'Python.lib.python3.5.site-packages.future.moves.dbm',
              'Python.lib.python3.5.site-packages.future.moves.html',
              'Python.lib.python3.5.site-packages.future.moves.http',
              'Python.lib.python3.5.site-packages.future.moves.test',
              'Python.lib.python3.5.site-packages.future.moves.urllib',
              'Python.lib.python3.5.site-packages.future.moves.xmlrpc',
              'Python.lib.python3.5.site-packages.future.moves.tkinter',
              'Python.lib.python3.5.site-packages.future.tests', 'Python.lib.python3.5.site-packages.future.types',
              'Python.lib.python3.5.site-packages.future.utils', 'Python.lib.python3.5.site-packages.future.builtins',
              'Python.lib.python3.5.site-packages.future.backports',
              'Python.lib.python3.5.site-packages.future.backports.html',
              'Python.lib.python3.5.site-packages.future.backports.http',
              'Python.lib.python3.5.site-packages.future.backports.test',
              'Python.lib.python3.5.site-packages.future.backports.email',
              'Python.lib.python3.5.site-packages.future.backports.email.mime',
              'Python.lib.python3.5.site-packages.future.backports.urllib',
              'Python.lib.python3.5.site-packages.future.backports.xmlrpc',
              'Python.lib.python3.5.site-packages.future.standard_library', 'Python.lib.python3.5.site-packages.serial',
              'Python.lib.python3.5.site-packages.serial.tools', 'Python.lib.python3.5.site-packages.serial.threaded',
              'Python.lib.python3.5.site-packages.serial.urlhandler', 'Python.lib.python3.5.site-packages.astroid',
              'Python.lib.python3.5.site-packages.astroid.interpreter',
              'Python.lib.python3.5.site-packages.astroid.interpreter._import',
              'Python.lib.python3.5.site-packages.iso8601', 'Python.lib.python3.5.site-packages.pyqtgraph',
              'Python.lib.python3.5.site-packages.pyqtgraph.util',
              'Python.lib.python3.5.site-packages.pyqtgraph.util.colorama',
              'Python.lib.python3.5.site-packages.pyqtgraph.tests',
              'Python.lib.python3.5.site-packages.pyqtgraph.canvas',
              'Python.lib.python3.5.site-packages.pyqtgraph.opengl',
              'Python.lib.python3.5.site-packages.pyqtgraph.opengl.items',
              'Python.lib.python3.5.site-packages.pyqtgraph.console',
              'Python.lib.python3.5.site-packages.pyqtgraph.pixmaps',
              'Python.lib.python3.5.site-packages.pyqtgraph.widgets',
              'Python.lib.python3.5.site-packages.pyqtgraph.dockarea',
              'Python.lib.python3.5.site-packages.pyqtgraph.examples',
              'Python.lib.python3.5.site-packages.pyqtgraph.examples.optics',
              'Python.lib.python3.5.site-packages.pyqtgraph.examples.relativity',
              'Python.lib.python3.5.site-packages.pyqtgraph.examples.verlet_chain',
              'Python.lib.python3.5.site-packages.pyqtgraph.exporters',
              'Python.lib.python3.5.site-packages.pyqtgraph.exporters.tests',
              'Python.lib.python3.5.site-packages.pyqtgraph.flowchart',
              'Python.lib.python3.5.site-packages.pyqtgraph.flowchart.library',
              'Python.lib.python3.5.site-packages.pyqtgraph.imageview',
              'Python.lib.python3.5.site-packages.pyqtgraph.metaarray',
              'Python.lib.python3.5.site-packages.pyqtgraph.multiprocess',
              'Python.lib.python3.5.site-packages.pyqtgraph.GraphicsScene',
              'Python.lib.python3.5.site-packages.pyqtgraph.graphicsItems',
              'Python.lib.python3.5.site-packages.pyqtgraph.graphicsItems.ViewBox',
              'Python.lib.python3.5.site-packages.pyqtgraph.graphicsItems.PlotItem',
              'Python.lib.python3.5.site-packages.pyqtgraph.parametertree',
              'Python.lib.python3.5.site-packages.pyximport', 'Python.lib.python3.5.site-packages.typed_ast',
              'Python.lib.python3.5.site-packages.setuptools', 'Python.lib.python3.5.site-packages.setuptools.extern',
              'Python.lib.python3.5.site-packages.setuptools._vendor',
              'Python.lib.python3.5.site-packages.setuptools._vendor.packaging',
              'Python.lib.python3.5.site-packages.setuptools.command', 'Python.lib.python3.5.site-packages.libfuturize',
              'Python.lib.python3.5.site-packages.libfuturize.fixes',
              'Python.lib.python3.5.site-packages.libpasteurize',
              'Python.lib.python3.5.site-packages.libpasteurize.fixes',
              'Python.lib.python3.5.site-packages.pkg_resources',
              'Python.lib.python3.5.site-packages.pkg_resources.extern',
              'Python.lib.python3.5.site-packages.pkg_resources._vendor',
              'Python.lib.python3.5.site-packages.pkg_resources._vendor.packaging',
              'Python.lib.python3.5.site-packages.lazy_object_proxy', 'Python.lib64.python3.5.site-packages.pip',
              'Python.lib64.python3.5.site-packages.pip._vendor',
              'Python.lib64.python3.5.site-packages.pip._vendor.idna',
              'Python.lib64.python3.5.site-packages.pip._vendor.pytoml',
              'Python.lib64.python3.5.site-packages.pip._vendor.certifi',
              'Python.lib64.python3.5.site-packages.pip._vendor.chardet',
              'Python.lib64.python3.5.site-packages.pip._vendor.chardet.cli',
              'Python.lib64.python3.5.site-packages.pip._vendor.distlib',
              'Python.lib64.python3.5.site-packages.pip._vendor.distlib._backport',
              'Python.lib64.python3.5.site-packages.pip._vendor.msgpack',
              'Python.lib64.python3.5.site-packages.pip._vendor.urllib3',
              'Python.lib64.python3.5.site-packages.pip._vendor.urllib3.util',
              'Python.lib64.python3.5.site-packages.pip._vendor.urllib3.contrib',
              'Python.lib64.python3.5.site-packages.pip._vendor.urllib3.contrib._securetransport',
              'Python.lib64.python3.5.site-packages.pip._vendor.urllib3.packages',
              'Python.lib64.python3.5.site-packages.pip._vendor.urllib3.packages.backports',
              'Python.lib64.python3.5.site-packages.pip._vendor.urllib3.packages.ssl_match_hostname',
              'Python.lib64.python3.5.site-packages.pip._vendor.colorama',
              'Python.lib64.python3.5.site-packages.pip._vendor.html5lib',
              'Python.lib64.python3.5.site-packages.pip._vendor.html5lib._trie',
              'Python.lib64.python3.5.site-packages.pip._vendor.html5lib.filters',
              'Python.lib64.python3.5.site-packages.pip._vendor.html5lib.treewalkers',
              'Python.lib64.python3.5.site-packages.pip._vendor.html5lib.treeadapters',
              'Python.lib64.python3.5.site-packages.pip._vendor.html5lib.treebuilders',
              'Python.lib64.python3.5.site-packages.pip._vendor.lockfile',
              'Python.lib64.python3.5.site-packages.pip._vendor.progress',
              'Python.lib64.python3.5.site-packages.pip._vendor.requests',
              'Python.lib64.python3.5.site-packages.pip._vendor.packaging',
              'Python.lib64.python3.5.site-packages.pip._vendor.cachecontrol',
              'Python.lib64.python3.5.site-packages.pip._vendor.cachecontrol.caches',
              'Python.lib64.python3.5.site-packages.pip._vendor.webencodings',
              'Python.lib64.python3.5.site-packages.pip._vendor.pkg_resources',
              'Python.lib64.python3.5.site-packages.pip._internal',
              'Python.lib64.python3.5.site-packages.pip._internal.req',
              'Python.lib64.python3.5.site-packages.pip._internal.vcs',
              'Python.lib64.python3.5.site-packages.pip._internal.utils',
              'Python.lib64.python3.5.site-packages.pip._internal.models',
              'Python.lib64.python3.5.site-packages.pip._internal.commands',
              'Python.lib64.python3.5.site-packages.pip._internal.operations',
              'Python.lib64.python3.5.site-packages.past', 'Python.lib64.python3.5.site-packages.past.tests',
              'Python.lib64.python3.5.site-packages.past.types', 'Python.lib64.python3.5.site-packages.past.utils',
              'Python.lib64.python3.5.site-packages.past.builtins',
              'Python.lib64.python3.5.site-packages.past.translation', 'Python.lib64.python3.5.site-packages.yaml',
              'Python.lib64.python3.5.site-packages.PyQt5', 'Python.lib64.python3.5.site-packages.PyQt5.uic',
              'Python.lib64.python3.5.site-packages.PyQt5.uic.Loader',
              'Python.lib64.python3.5.site-packages.PyQt5.uic.port_v2',
              'Python.lib64.python3.5.site-packages.PyQt5.uic.port_v3',
              'Python.lib64.python3.5.site-packages.PyQt5.uic.Compiler', 'Python.lib64.python3.5.site-packages.isort',
              'Python.lib64.python3.5.site-packages.numpy', 'Python.lib64.python3.5.site-packages.numpy.ma',
              'Python.lib64.python3.5.site-packages.numpy.ma.tests', 'Python.lib64.python3.5.site-packages.numpy.doc',
              'Python.lib64.python3.5.site-packages.numpy.fft', 'Python.lib64.python3.5.site-packages.numpy.fft.tests',
              'Python.lib64.python3.5.site-packages.numpy.lib', 'Python.lib64.python3.5.site-packages.numpy.lib.tests',
              'Python.lib64.python3.5.site-packages.numpy.core',
              'Python.lib64.python3.5.site-packages.numpy.core.tests',
              'Python.lib64.python3.5.site-packages.numpy.f2py',
              'Python.lib64.python3.5.site-packages.numpy.f2py.tests',
              'Python.lib64.python3.5.site-packages.numpy.tests', 'Python.lib64.python3.5.site-packages.numpy.compat',
              'Python.lib64.python3.5.site-packages.numpy.compat.tests',
              'Python.lib64.python3.5.site-packages.numpy.linalg',
              'Python.lib64.python3.5.site-packages.numpy.linalg.tests',
              'Python.lib64.python3.5.site-packages.numpy.random',
              'Python.lib64.python3.5.site-packages.numpy.random.tests',
              'Python.lib64.python3.5.site-packages.numpy.testing',
              'Python.lib64.python3.5.site-packages.numpy.testing.tests',
              'Python.lib64.python3.5.site-packages.numpy.testing._private',
              'Python.lib64.python3.5.site-packages.numpy.distutils',
              'Python.lib64.python3.5.site-packages.numpy.distutils.tests',
              'Python.lib64.python3.5.site-packages.numpy.distutils.command',
              'Python.lib64.python3.5.site-packages.numpy.distutils.fcompiler',
              'Python.lib64.python3.5.site-packages.numpy.matrixlib',
              'Python.lib64.python3.5.site-packages.numpy.matrixlib.tests',
              'Python.lib64.python3.5.site-packages.numpy.polynomial',
              'Python.lib64.python3.5.site-packages.numpy.polynomial.tests',
              'Python.lib64.python3.5.site-packages.wrapt', 'Python.lib64.python3.5.site-packages.Cython',
              'Python.lib64.python3.5.site-packages.Cython.Plex', 'Python.lib64.python3.5.site-packages.Cython.Build',
              'Python.lib64.python3.5.site-packages.Cython.Build.Tests',
              'Python.lib64.python3.5.site-packages.Cython.Tests',
              'Python.lib64.python3.5.site-packages.Cython.Runtime',
              'Python.lib64.python3.5.site-packages.Cython.Tempita',
              'Python.lib64.python3.5.site-packages.Cython.Utility',
              'Python.lib64.python3.5.site-packages.Cython.Compiler',
              'Python.lib64.python3.5.site-packages.Cython.Compiler.Tests',
              'Python.lib64.python3.5.site-packages.Cython.Debugger',
              'Python.lib64.python3.5.site-packages.Cython.Debugger.Tests',
              'Python.lib64.python3.5.site-packages.Cython.Distutils', 'Python.lib64.python3.5.site-packages.future',
              'Python.lib64.python3.5.site-packages.future.moves',
              'Python.lib64.python3.5.site-packages.future.moves.dbm',
              'Python.lib64.python3.5.site-packages.future.moves.html',
              'Python.lib64.python3.5.site-packages.future.moves.http',
              'Python.lib64.python3.5.site-packages.future.moves.test',
              'Python.lib64.python3.5.site-packages.future.moves.urllib',
              'Python.lib64.python3.5.site-packages.future.moves.xmlrpc',
              'Python.lib64.python3.5.site-packages.future.moves.tkinter',
              'Python.lib64.python3.5.site-packages.future.tests', 'Python.lib64.python3.5.site-packages.future.types',
              'Python.lib64.python3.5.site-packages.future.utils',
              'Python.lib64.python3.5.site-packages.future.builtins',
              'Python.lib64.python3.5.site-packages.future.backports',
              'Python.lib64.python3.5.site-packages.future.backports.html',
              'Python.lib64.python3.5.site-packages.future.backports.http',
              'Python.lib64.python3.5.site-packages.future.backports.test',
              'Python.lib64.python3.5.site-packages.future.backports.email',
              'Python.lib64.python3.5.site-packages.future.backports.email.mime',
              'Python.lib64.python3.5.site-packages.future.backports.urllib',
              'Python.lib64.python3.5.site-packages.future.backports.xmlrpc',
              'Python.lib64.python3.5.site-packages.future.standard_library',
              'Python.lib64.python3.5.site-packages.serial', 'Python.lib64.python3.5.site-packages.serial.tools',
              'Python.lib64.python3.5.site-packages.serial.threaded',
              'Python.lib64.python3.5.site-packages.serial.urlhandler', 'Python.lib64.python3.5.site-packages.astroid',
              'Python.lib64.python3.5.site-packages.astroid.interpreter',
              'Python.lib64.python3.5.site-packages.astroid.interpreter._import',
              'Python.lib64.python3.5.site-packages.iso8601', 'Python.lib64.python3.5.site-packages.pyqtgraph',
              'Python.lib64.python3.5.site-packages.pyqtgraph.util',
              'Python.lib64.python3.5.site-packages.pyqtgraph.util.colorama',
              'Python.lib64.python3.5.site-packages.pyqtgraph.tests',
              'Python.lib64.python3.5.site-packages.pyqtgraph.canvas',
              'Python.lib64.python3.5.site-packages.pyqtgraph.opengl',
              'Python.lib64.python3.5.site-packages.pyqtgraph.opengl.items',
              'Python.lib64.python3.5.site-packages.pyqtgraph.console',
              'Python.lib64.python3.5.site-packages.pyqtgraph.pixmaps',
              'Python.lib64.python3.5.site-packages.pyqtgraph.widgets',
              'Python.lib64.python3.5.site-packages.pyqtgraph.dockarea',
              'Python.lib64.python3.5.site-packages.pyqtgraph.examples',
              'Python.lib64.python3.5.site-packages.pyqtgraph.examples.optics',
              'Python.lib64.python3.5.site-packages.pyqtgraph.examples.relativity',
              'Python.lib64.python3.5.site-packages.pyqtgraph.examples.verlet_chain',
              'Python.lib64.python3.5.site-packages.pyqtgraph.exporters',
              'Python.lib64.python3.5.site-packages.pyqtgraph.exporters.tests',
              'Python.lib64.python3.5.site-packages.pyqtgraph.flowchart',
              'Python.lib64.python3.5.site-packages.pyqtgraph.flowchart.library',
              'Python.lib64.python3.5.site-packages.pyqtgraph.imageview',
              'Python.lib64.python3.5.site-packages.pyqtgraph.metaarray',
              'Python.lib64.python3.5.site-packages.pyqtgraph.multiprocess',
              'Python.lib64.python3.5.site-packages.pyqtgraph.GraphicsScene',
              'Python.lib64.python3.5.site-packages.pyqtgraph.graphicsItems',
              'Python.lib64.python3.5.site-packages.pyqtgraph.graphicsItems.ViewBox',
              'Python.lib64.python3.5.site-packages.pyqtgraph.graphicsItems.PlotItem',
              'Python.lib64.python3.5.site-packages.pyqtgraph.parametertree',
              'Python.lib64.python3.5.site-packages.pyximport', 'Python.lib64.python3.5.site-packages.typed_ast',
              'Python.lib64.python3.5.site-packages.setuptools',
              'Python.lib64.python3.5.site-packages.setuptools.extern',
              'Python.lib64.python3.5.site-packages.setuptools._vendor',
              'Python.lib64.python3.5.site-packages.setuptools._vendor.packaging',
              'Python.lib64.python3.5.site-packages.setuptools.command',
              'Python.lib64.python3.5.site-packages.libfuturize',
              'Python.lib64.python3.5.site-packages.libfuturize.fixes',
              'Python.lib64.python3.5.site-packages.libpasteurize',
              'Python.lib64.python3.5.site-packages.libpasteurize.fixes',
              'Python.lib64.python3.5.site-packages.pkg_resources',
              'Python.lib64.python3.5.site-packages.pkg_resources.extern',
              'Python.lib64.python3.5.site-packages.pkg_resources._vendor',
              'Python.lib64.python3.5.site-packages.pkg_resources._vendor.packaging',
              'Python.lib64.python3.5.site-packages.lazy_object_proxy'],
    url='https://github.com/gdroumpalis/Electro',
    license='GPL',
    author='terminux',
    author_email='',
    description=''
)
