# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/terminux/Documents/Projects/Electro/Resources/mainui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(852, 749)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalGroupBox.sizePolicy().hasHeightForWidth())
        self.horizontalGroupBox.setSizePolicy(sizePolicy)
        self.horizontalGroupBox.setObjectName("horizontalGroupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalGroupBox)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.horizontalGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.selecteddevicecombobox = QtWidgets.QComboBox(self.horizontalGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selecteddevicecombobox.sizePolicy().hasHeightForWidth())
        self.selecteddevicecombobox.setSizePolicy(sizePolicy)
        self.selecteddevicecombobox.setMinimumSize(QtCore.QSize(180, 0))
        self.selecteddevicecombobox.setMaximumSize(QtCore.QSize(250, 16777215))
        self.selecteddevicecombobox.setObjectName("selecteddevicecombobox")
        self.horizontalLayout.addWidget(self.selecteddevicecombobox)
        self.label_2 = QtWidgets.QLabel(self.horizontalGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.speedspinbox = QtWidgets.QSpinBox(self.horizontalGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.speedspinbox.sizePolicy().hasHeightForWidth())
        self.speedspinbox.setSizePolicy(sizePolicy)
        self.speedspinbox.setMinimum(1200)
        self.speedspinbox.setMaximum(10000000)
        self.speedspinbox.setObjectName("speedspinbox")
        self.horizontalLayout.addWidget(self.speedspinbox)
        self.verticalLayout.addWidget(self.horizontalGroupBox)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_2 = QtWidgets.QFrame(self.tab)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.liveplottingcheckbox = QtWidgets.QCheckBox(self.frame_2)
        self.liveplottingcheckbox.setGeometry(QtCore.QRect(10, 10, 111, 24))
        self.liveplottingcheckbox.setObjectName("liveplottingcheckbox")
        self.loggingcheckbox = QtWidgets.QCheckBox(self.frame_2)
        self.loggingcheckbox.setGeometry(QtCore.QRect(130, 10, 96, 24))
        self.loggingcheckbox.setObjectName("loggingcheckbox")
        self.filecheckbox = QtWidgets.QCheckBox(self.frame_2)
        self.filecheckbox.setGeometry(QtCore.QRect(230, 10, 131, 24))
        self.filecheckbox.setObjectName("filecheckbox")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(20, 47, 131, 21))
        self.label_3.setObjectName("label_3")
        self.filepathlineedit = QtWidgets.QLineEdit(self.frame_2)
        self.filepathlineedit.setGeometry(QtCore.QRect(150, 40, 171, 34))
        self.filepathlineedit.setObjectName("filepathlineedit")
        self.filepathtoolbutton = QtWidgets.QToolButton(self.frame_2)
        self.filepathtoolbutton.setGeometry(QtCore.QRect(320, 40, 36, 34))
        self.filepathtoolbutton.setObjectName("filepathtoolbutton")
        self.gridLayout.addWidget(self.frame_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_3 = QtWidgets.QFrame(self.tab_2)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.filepathlineedit_2 = QtWidgets.QLineEdit(self.frame_3)
        self.filepathlineedit_2.setGeometry(QtCore.QRect(150, 53, 271, 34))
        self.filepathlineedit_2.setObjectName("filepathlineedit_2")
        self.filepathtoolbutton_2 = QtWidgets.QToolButton(self.frame_3)
        self.filepathtoolbutton_2.setGeometry(QtCore.QRect(420, 53, 36, 34))
        self.filepathtoolbutton_2.setObjectName("filepathtoolbutton_2")
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        self.label_4.setGeometry(QtCore.QRect(20, 60, 131, 21))
        self.label_4.setObjectName("label_4")
        self.spinBox_2 = QtWidgets.QSpinBox(self.frame_3)
        self.spinBox_2.setGeometry(QtCore.QRect(150, 10, 104, 34))
        self.spinBox_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_2.setMaximum(0)
        self.spinBox_2.setObjectName("spinBox_2")
        self.spinBox_3 = QtWidgets.QSpinBox(self.frame_3)
        self.spinBox_3.setGeometry(QtCore.QRect(333, 10, 121, 34))
        self.spinBox_3.setMinimum(200)
        self.spinBox_3.setMaximum(5000)
        self.spinBox_3.setObjectName("spinBox_3")
        self.label_5 = QtWidgets.QLabel(self.frame_3)
        self.label_5.setGeometry(QtCore.QRect(20, 20, 65, 18))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame_3)
        self.label_6.setGeometry(QtCore.QRect(310, 18, 41, 21))
        self.label_6.setObjectName("label_6")
        self.autoopenfilecheckbox = QtWidgets.QCheckBox(self.frame_3)
        self.autoopenfilecheckbox.setGeometry(QtCore.QRect(15, 97, 111, 24))
        self.autoopenfilecheckbox.setObjectName("autoopenfilecheckbox")
        self.gridLayout_2.addWidget(self.frame_3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.addhandlerbutton = QtWidgets.QPushButton(self.tab_3)
        self.addhandlerbutton.setObjectName("addhandlerbutton")
        self.verticalLayout_2.addWidget(self.addhandlerbutton)
        self.removehandlerbutton = QtWidgets.QPushButton(self.tab_3)
        self.removehandlerbutton.setObjectName("removehandlerbutton")
        self.verticalLayout_2.addWidget(self.removehandlerbutton)
        self.handlerslist = QtWidgets.QListWidget(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.handlerslist.sizePolicy().hasHeightForWidth())
        self.handlerslist.setSizePolicy(sizePolicy)
        self.handlerslist.setObjectName("handlerslist")
        self.verticalLayout_2.addWidget(self.handlerslist)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.frame = QtWidgets.QFrame(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_7 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        self.comboBox = QtWidgets.QComboBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_3.addWidget(self.comboBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3.addWidget(self.frame_4)
        self.horizontalLayout_2.addWidget(self.frame)
        self.tabWidget.addTab(self.tab_3, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 852, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setEnabled(True)
        self.menuSettings.setObjectName("menuSettings")
        self.menuPlotting = QtWidgets.QMenu(self.menubar)
        self.menuPlotting.setObjectName("menuPlotting")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBar.sizePolicy().hasHeightForWidth())
        self.toolBar.setSizePolicy(sizePolicy)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.LeftToolBarArea, self.toolBar)
        self.actionOpen_Plot_File = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/open/Icons/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen_Plot_File.setIcon(icon)
        self.actionOpen_Plot_File.setObjectName("actionOpen_Plot_File")
        self.actionClose = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/close/Icons/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClose.setIcon(icon1)
        self.actionClose.setObjectName("actionClose")
        self.actionopen_settings = QtWidgets.QAction(MainWindow)
        self.actionopen_settings.setEnabled(False)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/settings/Icons/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionopen_settings.setIcon(icon2)
        self.actionopen_settings.setVisible(False)
        self.actionopen_settings.setObjectName("actionopen_settings")
        self.actionStart_Plotting = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/start/Icons/start.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStart_Plotting.setIcon(icon3)
        self.actionStart_Plotting.setVisible(True)
        self.actionStart_Plotting.setObjectName("actionStart_Plotting")
        self.actionPlottings_UI = QtWidgets.QAction(MainWindow)
        self.actionPlottings_UI.setEnabled(False)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/plot/Icons/plot.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPlottings_UI.setIcon(icon4)
        self.actionPlottings_UI.setVisible(False)
        self.actionPlottings_UI.setObjectName("actionPlottings_UI")
        self.actionRefresh_Devices = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/refresh/Icons/refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRefresh_Devices.setIcon(icon5)
        self.actionRefresh_Devices.setObjectName("actionRefresh_Devices")
        self.actionClear_Device_List = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/clear/Icons/clear.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClear_Device_List.setIcon(icon6)
        self.actionClear_Device_List.setObjectName("actionClear_Device_List")
        self.menuFile.addAction(self.actionOpen_Plot_File)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose)
        self.menuSettings.addAction(self.actionopen_settings)
        self.menuSettings.addAction(self.actionRefresh_Devices)
        self.menuSettings.addAction(self.actionClear_Device_List)
        self.menuPlotting.addAction(self.actionStart_Plotting)
        self.menuPlotting.addAction(self.actionPlottings_UI)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuPlotting.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.toolBar.addAction(self.actionOpen_Plot_File)
        self.toolBar.addAction(self.actionStart_Plotting)
        self.toolBar.addAction(self.actionRefresh_Devices)
        self.toolBar.addAction(self.actionClear_Device_List)
        self.toolBar.addAction(self.actionPlottings_UI)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Electro"))
        self.horizontalGroupBox.setTitle(_translate("MainWindow", "USB and Plotting Settings"))
        self.label.setText(_translate("MainWindow", "USB Device"))
        self.label_2.setText(_translate("MainWindow", "Speed"))
        self.liveplottingcheckbox.setText(_translate("MainWindow", "Live Plotting"))
        self.loggingcheckbox.setText(_translate("MainWindow", "Logging"))
        self.filecheckbox.setText(_translate("MainWindow", "File Recording"))
        self.label_3.setText(_translate("MainWindow", "Filepath Recording"))
        self.filepathtoolbutton.setText(_translate("MainWindow", "..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Live Plotting"))
        self.filepathtoolbutton_2.setText(_translate("MainWindow", "..."))
        self.label_4.setText(_translate("MainWindow", "Filepath Recording"))
        self.label_5.setText(_translate("MainWindow", "From"))
        self.label_6.setText(_translate("MainWindow", "To"))
        self.autoopenfilecheckbox.setText(_translate("MainWindow", "Auto Open"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Sampling"))
        self.addhandlerbutton.setText(_translate("MainWindow", "Add Handler"))
        self.removehandlerbutton.setText(_translate("MainWindow", "Remove Handler"))
        self.label_7.setText(_translate("MainWindow", "Action Type"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Handlers"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuSettings.setTitle(_translate("MainWindow", "Electro"))
        self.menuPlotting.setTitle(_translate("MainWindow", "Plotting"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionOpen_Plot_File.setText(_translate("MainWindow", "Open Plot File"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionopen_settings.setText(_translate("MainWindow", "Settings"))
        self.actionStart_Plotting.setText(_translate("MainWindow", "Start Plotting"))
        self.actionPlottings_UI.setText(_translate("MainWindow", "Plottings UI (exp)"))
        self.actionRefresh_Devices.setText(_translate("MainWindow", "Refresh Devices"))
        self.actionClear_Device_List.setText(_translate("MainWindow", "Clear Device List"))

import ElectroRes_rc
