# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/terminux/Documents/Projects/Electro/Resources/mainui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(781, 488)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 781, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuPlotting = QtWidgets.QMenu(self.menubar)
        self.menuPlotting.setObjectName("menuPlotting")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.LeftToolBarArea, self.toolBar)
        self.actionOpen_Plot_File = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/open/Icons/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen_Plot_File.setIcon(icon)
        self.actionOpen_Plot_File.setObjectName("actionOpen_Plot_File")
        self.actionClose = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/close/Icons/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClose.setIcon(icon1)
        self.actionClose.setObjectName("actionClose")
        self.actionopen_settings = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/settings/Icons/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionopen_settings.setIcon(icon2)
        self.actionopen_settings.setObjectName("actionopen_settings")
        self.actionStart_Plotting = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/start/Icons/start.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStart_Plotting.setIcon(icon3)
        self.actionStart_Plotting.setObjectName("actionStart_Plotting")
        self.actionPlottings_UI = QtWidgets.QAction(MainWindow)
        self.actionPlottings_UI.setObjectName("actionPlottings_UI")
        self.menuFile.addAction(self.actionOpen_Plot_File)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose)
        self.menuSettings.addAction(self.actionopen_settings)
        self.menuPlotting.addAction(self.actionStart_Plotting)
        self.menuPlotting.addAction(self.actionPlottings_UI)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuPlotting.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.toolBar.addAction(self.actionOpen_Plot_File)
        self.toolBar.addAction(self.actionStart_Plotting)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Electro"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuSettings.setTitle(_translate("MainWindow", "Proc"))
        self.menuPlotting.setTitle(_translate("MainWindow", "Plotting"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionOpen_Plot_File.setText(_translate("MainWindow", "Open Plot File"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionopen_settings.setText(_translate("MainWindow", "Settings"))
        self.actionStart_Plotting.setText(_translate("MainWindow", "Start Plotting"))
        self.actionPlottings_UI.setText(_translate("MainWindow", "Plottings UI (exp)"))

import ElectroRes_rc
